### ISSUE TITLE
Update to documentation to reference test image

### ISSUE THREAD

**Issue by janzheng** [ellinium/plaque_size_tool#1]
Hi there!

Could you please update the documentation to reference an image included in the `Test_plates/large` folder? Currently it says `Test_plates/large/29.tif` but I'm just suggesting an update to `Test_plates/large/Plate_2.tif` 

It's a really really small change, but maybe it'll help someone new to CLIs along the way!

Thanks, it's a great tool!

**Comment by ellinium** [comment]
Hi Jan!
Thank you for the issue. I'v updated Readme according to the supplementary User Manual, it should be up-to-date now.
