### ISSUE TITLE
Plaque_size_tool in Linux 

### ISSUE THREAD

**Issue by biocdgv** [ellinium/plaque_size_tool#2]
Dear Ellina,

Such an interesting and useful tool. However, I was wondering if are you planning to make this tool available for Linux OS as well? For example, I am a Linux user and I just give your tool a try, and naturally, it did not install. Thus, I think it would have a wider impact if it can be also installed in Linux OS.

Sincerely,

**Comment by ellinium** [comment]
Hi,
Thank you for the question.
You can use it on any OS that support Python3. I haven't tested it directly on Linux, but it should work on it as Linux supports Python.

**Comment by biocdgv** [comment]
Hi!

I have python 3.8.5 but plaque_size_tool does not install. I just ran : 

`pip3 install plaque_size_tool.py` 
 
and got:

![imagen](https://user-images.githubusercontent.com/57162811/123200915-480de900-d477-11eb-9818-92d3cb4a89ac.png)
