### ISSUE TITLE
Plaque_size_tool did not install in Ubuntu 18.04.05 LTS

### ISSUE THREAD

**Issue by biocdgv** [ellinium/plaque_size_tool#3]
Hello,

Quoting from #2 , I was not able to install plaque_size_tool in Ubuntu 18.04.05 LTS. I have already installed python3 (v3.8.5) as well as pip3.

Here is the output after running `pip3 install plaque_size_tool.py` :
 
![imagen](https://user-images.githubusercontent.com/57162811/123200915-480de900-d477-11eb-9818-92d3cb4a89ac.png)

Thanks in advance!

**Comment by ellinium** [comment]
what's pip3 version installed?

**Comment by biocdgv** [comment]
pip 20.2.4

**Comment by ellinium** [comment]
can you please update pip3 to the latest version (21) and re-test? pip3 install --upgrade pip

**Comment by biocdgv** [comment]
Now my pip3 is in 21.1.2 version. However, it outputs the same error as in 

> Hello,
> 
> Quoting from #2 , I was not able to install plaque_size_tool in Ubuntu 18.04.05 LTS. I have already installed python3 (v3.8.5) as well as pip3.
> 
> Here is the output after running `pip3 install plaque_size_tool.py` :
> 
> ![imagen](https://user-images.githubusercontent.com/57162811/123200915-480de900-d477-11eb-9818-92d3cb4a89ac.png)
> 
> Thanks in advance!

**Comment by ellinium** [comment]
Thanks for testing! I'm going to try to install PST on Ubuntu via Docker and will get back to you as soon as I get any results.

**Comment by ellinium** [comment]
I think there is a small error in the command you're executing:
It should be pip3 install plaque-size-tool, not pip3 install plaque_size_tool.py.
Can you please re-test?

**Comment by biocdgv** [comment]
Yep, it installed correctly after running 
`pip3 install plaque-size-tool`

Thanks!!

**Comment by ellinium** [comment]
Thank you for using the tool!
